### ISSUE TITLE
Mod name conflicts with existing brands

### ISSUE THREAD

**Issue by Mailaender** [AttacqueSuperior/ValiantShades#1]
http://valianthearts.ubi.com/game/ might cause you legal trouble.

**Comment by GraionDilach** [comment]
Wonderful. I really need to go with that alternative name - or come up with something.

**Comment by GraionDilach** [comment]
Resolved. Google gave nothing troublesome to Valiant Shades. Valiant Minds was the other original name but that also got a limited company as a namesake.
